[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ids_ips_course"
authors = [{name = "Elie Kfoury", email = "ekfoury@email.sc.edu"}]
dynamic = ["version", "description"]

